title: Brian Toulouse # your name (or website title) here
logo:     "images/oooo.plus_136.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent graduated and am looking to make a career change, I have been working in a professional environment for over ten years. <br>
  I have held several customer facing positions in a corporate environment. I have developed a strong work ethic; I know what it takes to succeed and how to work with a team to accomplish a goal. 
  <br>
  I am really looking forward to combining my prior experience with the knowledge I have gained while pursuing my degree. 
  <br><br>
  <a href="https://www.linkedin.com/in/briantoulouse/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
