title: Brian Toulouse # your name (or website title) here
logo: "images/Profile Pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Motivated entry level software engineer excited to begin applying the knowledge <br><br>
  and skills I have gained in my studies to real world application. I enjoy finding <br><br>
  creative solutions to tough problems, creating new programs, and optimizing <br><br>
  existing programs. I am a quick learner, action oriented and strategic thinker. 
  
  description: >
  <br><br>
  <a href="https://www.linkedin.com/in/briantoulouse/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
