title: Brian Toulouse # your name (or website title) here
logo: "images/oooo.plus_12 (1).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Motivated entry level software engineer excited to begin applying the knowledge and skills I have gained in my studies to real world application.
  <br><br>
  I enjoy finding creative solutions to tough problems, creating new programs, and optimizing existing programs. I am a quick learner, action oriented and strategic thinker. 
  <br><br>
  <a href="https://www.linkedin.com/in/briantoulouse/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
